### ISSUE TITLE
Portfolio Checklist

### ISSUE THREAD

**Issue by mseip** [mseip/Portfolio#1]
# Portfolio Checklist

## Things to consider including in your portfolio

- [x] Samples of earlier and later work to document your growth
- [x] Awards and recognition
- [x] Samples of your favourite, best and most important work
- [x] LinkedIN
- [x] Resume
- [x] Examples of your planning and organizing skills
- [x] Work experience and volunteer experience

## Your finished portfolio must meet the following key requirements

- [x] Be of high quality
- [x] Include examples of your work
- [x] Be free of grammatical errors
- [x] Responsive
- [x] Developed for online viewing and deployment
- [x] Contain original content or content that is appropriately licensed for your use.
- [x] Be complete
- [x] Responsive
- [x] Animations

## Optional Ideas

- [x] Skill list
- [x] Timeline
- [x] Work showcase
- [x] Contact form (functional)
